variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build_vincss:
  environment:
    name: vincss
  stage: build
  script:
    - docker build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_WS_URL=$REACT_APP_WS_URL -t cystack/locker-web-vincss -f staging.Dockerfile .
    - docker push cystack/locker-web-vincss
  tags:
    - cs_newgen
  only:
    - vincss
    - tags

