export default {
  // Core
  SET_IS_LOCKED: 'SET_IS_LOCKED',
  SET_IS_SYNC: 'SET_IS_SYNC',
  SET_SYNCING: 'SET_SYNCING',

  // System
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_IS_MOBILE: 'SET_IS_MOBILE',
  SET_IS_COLUMN: 'SET_IS_COLUMN',
  SET_COLLAPSED: 'SET_COLLAPSED',
  SET_CACHE_DATA: 'SET_CACHE_DATA',
  SET_IS_CLOUD: 'SET_IS_CLOUD',
  SET_IS_SCROLL_TO_TOP: 'SET_IS_SCROLL_TO_TOP',

  // Auth
  SET_USER_INFO: 'SET_USER_INFO',
  SET_FACTOR2: 'SET_FACTOR2',
  SET_LOGIN_INFO: 'SET_LOGIN_INFO',
}