export default {
  jsCore: null,
  endpoint: {},
  constants: {},
  routers: {},
  menus: {},
  patterns: {},
  rules: {},
  store: {},
  keys: {},
  confirm: () => {},
  notification: () => {},
  navigate: () => {},
  pushSuccess: () => {},
  pushError: () => {},
}